# Site settings
title: "Welcome to Prestigei Blog"
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: prestigei@prestigei.com
description: > # this means to ignore newlines until "url:"
  This is a blog site of Prestigei institute
url: "" # the base hostname & protocol for your site
baseurl: "/p-blog" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username: jekyll

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
